[tool.black]
line-length = 200
target-version = ["py312"]

[tool.ruff]
line-length = 200
indent-width = 4
target-version = "py312"

[tool.ruff.lint]
select = ["E", "F"]
ignore = ["E303"]
preview = true

[tool.ruff.format]
quote-style = "single"
indent-style = "tab"
