paths:
  raw_data: "data/raw"
  processed_data: "data/processed"
  archived_data: "data/archive"

file_names_inputs:
  tax_brackets: "artifacts/flat_files/tax_brackets.csv"
  commsec_transactions_in: "confirmation_details.csv"

file_names_outputs:
  current_portfolio: "current_portfolio.csv"
  capital_gains: "capital_gains.csv"
  tax_statement: "tax_statement.csv"
  inflows: "inflows.csv"

fixed_values:
  base_salary: 121000
  medibank_cost: 1500

other_settings:
  debug_mode: true


