paths:
  tax_brackets_file: "artifacts/flat_files/tax_brackets.csv"
  raw_data: "data/raw"
  processed_data: "data/processed"

fixed_values:
  base_salary: 121000
  medibank_cost: 1500
  levy_rate: 0.02

# source_info for income, hecs and medibank tax brackets. first bool is "is_tax" (converse is rebate) and second is whether its cumulatively added or just flat rate
bracket_source_info:
  income:
    - true
    - true
  hecs:
    - true
    - false
  medibank:
    - false
    - false

other_settings:
  debug_mode: true


